park/urls.py
from django.conf.urls import url
from . import views

app_name = 'park'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^search/$', views.search, name='search'),
    url(r'^add_animal/$', views.add_pending, name='add_animal'),
    url(r'^(?P<class_name>[A-Za-z0-9ก-ฮ]+)/$', views.animal_list, name='animal_list'),
    url(r'^animal/(?P<animal_name>[A-Za-z0-9ก-ฮ_]+)$', views.animal_data, name='animal_data'),
    url(r'^animal/(?P<animal_name>[A-Za-z0-9ก-ฮ_]+)/add_pic/$', views.add_picture, name='add_picture'),
]

projectzoo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('park.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

park/models.py
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from uuid import uuid4
import os

STATUS_CHOICES = (
    ('Pending','Pending'),
    ('Published','Published'),
)

CLASS_CHOICES = (
    ('Mammal','Mammal'),
    ('Reptile','Reptile'),
    ('Amphibian','Amphibian'),
    ('Fish','Fish'),
    ('Bird','Bird'),
)

def path_and_rename(instance, filename):
    upload_to = 'animal_pic/' + str(instance.animal.name)
    # get filename
    if instance.animal.name:
        filename = '{}.{}'.format(instance.animal.name, "jpg")
    else:
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, "jpg")
    # return the whole path to the file
    return os.path.join(upload_to, filename)

class Animal(models.Model):
    thai_name = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    class_name = models.CharField(max_length=10,choices=CLASS_CHOICES)
    order = models.CharField(max_length=200)
    family = models.CharField(max_length=200)
    info = models.TextField(null=True, blank=True)
    habitat = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,null=True, blank=True)

    def __str__(self):
        return self.name
    
    def url_name(self):
        return self.name.replace(' ', '_')

class AnimalImage(models.Model):
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, related_name='image')
    image = models.ImageField(upload_to=path_and_rename)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,null=True, blank=True)

@receiver(pre_delete, sender=AnimalImage)
def pic_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.image.delete(False)

park/views.py
from django.http import Http404
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Animal
from django.db.models import Q
from django.shortcuts import render_to_response
from django.template import RequestContext


def page_not_found(request):
    response = render_to_response('park/no_page.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response

def index(request):
    return render(request, 'park/home.html',
           {'all_animal':Animal.objects.filter(status="Published").count(),
            'mammal_num':Animal.objects.filter(status="Published",class_name="Mammal").count(),
            'reptile_num':Animal.objects.filter(status="Published",class_name="Reptile").count(),
            'bird_num':Animal.objects.filter(status="Published",class_name="Bird").count(),
            'fish_num':Animal.objects.filter(status="Published",class_name="Fish").count(),
            'amphibian_num':Animal.objects.filter(status="Published",class_name="Amphibian").count()})

def animal_list(request, class_name):
    all_class = ["All","Mammal","Reptile","Bird","Fish","Amphibian"]
    if(class_name == 'All'):
        list = Animal.objects.filter(status="Published").order_by('thai_name')
    elif(class_name in ('Mammal','Reptile','Bird','Fish','Amphibian')):
        list = Animal.objects.filter(status="Published",class_name=class_name).order_by('thai_name')
    else:
        return render(request, 'park/no_page.html')
    return render(request, 'park/animal_list.html',{'lists':list,'all_class':all_class,'class_now':class_name})
 
def animal_data(request, animal_name):
    try:
        animal = Animal.objects.get(name=animal_name.replace('_', ' '))
        image_list = animal.image.filter(status="Published").order_by('image')
        if(animal.status == "Published"):
            return render(request, 'park/animal_data.html',{'animal':animal,'image_list':image_list})
        else:
            raise
    except:
        return render(request, 'park/no_page.html')

def search(request):
    animal_list = []
    word = ""
    if(request.GET.get('word')):
        word = request.GET.get('word')
        filter_list = { 'name'  :   Q(name__icontains=word) | 
                                    Q(thai_name__icontains=word),
                        'order' :   Q(order__icontains=word),
                        'family':   Q(family__icontains=word),
                        'info'  :   Q(info__icontains=word),
                        'habitat':  Q(habitat__icontains=word)
                        }

        if(request.GET.get('search') == 'all'):
            animal_list = Animal.objects.filter(Q(status="Published",) &
                (
                Q(thai_name__icontains=word) |
                Q(name__icontains=word,) |
                Q(class_name__icontains=word,) |
                Q(order__icontains=word) |
                Q(family__icontains=word) |
                Q(info__icontains=word) |
                Q(habitat__icontains=word)
                )
            )
        else:
            search_by = request.GET.get('search')
            animal_list = Animal.objects.filter(Q(status="Published") & filter_list[search_by])

    return render(request, 'park/search.html',{'word':word, 'lists':animal_list})

def add_pending(request):
    error_message = ""
    complete_message = ""
    if(request.POST.get('submit')):
        if("" in (request.POST.get('name'),request.POST.get('thai_name'))):
            error_message = "กรุณากรอกชื่อของสัตว์ด้วยจ้า"
        else:
            animal = Animal(thai_name = request.POST.get('thai_name'),
                            name = request.POST.get('name'),
                            class_name = request.POST.get('class_name'),
                            order = request.POST.get('order'),
                            family = request.POST.get('family'),
                            info = request.POST.get('info'),
                            habitat = request.POST.get('habitat'),
                            status= "Pending")
            animal.save()

            for pic in request.FILES.getlist('pic_file'):
                animal.image.create(image=pic)
            
            complete_message = "ขอบคุณที่ช่วยเพิ่มข้อมูลให้กับเรา :)"
    return render(request, 'park/add_data.html',{'error_message':error_message,'complete_message':complete_message})

def add_picture(request,animal_name):
    animal = Animal.objects.get(name=animal_name.replace('_', ' '))
    for pic in request.FILES.getlist('pic_file'):
            animal.image.create(image=pic,status="Pending")
    image_list = animal.image.filter(status="Published").order_by('image')
    
    return HttpResponseRedirect(reverse('park:animal_data', args=(animal_name,)))

def about(request):
    return render(request, 'park/about.html')

park/templates/park/about.html
{% extends 'park/base.html' %}
{% load static %}

{% block title %}About{% endblock %}

{% block style_n_script %}
    <link rel="stylesheet" href="{% static '/css/list.css' %}">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
{% endblock %}

{% block header %}
<p id="main_page_head">About</p>
{% endblock %}

{% block content %}
    <div class="list_div">
        <a href="{% url 'park:index' %}"><button id='home' class="button button_menu">&#127968; Home</button></a><br>
    </div>

    <div class="about">
        <h2>เว็บ Animals</h2>
        <p style="text-indent:2em">เว็บนี้ได้ถูกสร้างขึ้นมาเพื่อที่จะรวบรวมข้อมูลพื้นฐานของสัตว์ต่างๆเอาไว้ ให้ผู้มาเยือนได้ศึกษาหาความรู้หรือจะอ่านเพลินๆกันก็ได้
            โดยภายในเว็บไซต์นี้จะมีส่วนประกอบต่างๆ ตามด้านล่างนี้เลย
        </p>

        <hr><br>
        <div style="text-align:center"><img src="{% static '/image/about/main.png' %}" width="480px" /></div>
        <h3>หน้าหลัก</h3>
        <p style="text-indent:2em">จะเป็นหน้าแรกเลยที่จะเจอเมื่อเข้ามาในเว็บไซต์ โดยจะมีปุ่มเพื่อเข้าไปสู่หน้าค้นหา และหน้ารายชื่อสัตว์ซึ่งจะแบ่งไว้ให้เป็นหมวดต่างๆแล้ว<br><br>
        </p>

        <hr><br>
        <div style="text-align:center">
            <img src="{% static '/image/about/list.png' %}" width="480px" /> &nbsp;
            <img src="{% static '/image/about/list2.png' %}" width="480px" />
        </div>
        <h3>หน้าแสดงรายชื่อสัตว์</h3>
        <p style="text-indent:2em">เป็นหน้าที่จะแสดงรายชื่อสัตว์ทั้งหมดที่มีข้อมูลอยู่ภายในเว็บไซต์ออกมา สามารถคลิกเข้าไปดูข้อมูลของสัตว์ตัวนั้นๆได้ ที่ด้านบนก็จะมีปุ่มใช้คัดกรองให้แสดงรายชื่อสัตว์เฉพาะหมวดหมู่ที่เลือกอยู่ได้<br><br>
        </p>

        <hr><br>
        <div style="text-align:center">
            <img src="{% static '/image/about/data.png' %}" width="480px" /> &nbsp;
            <img src="{% static '/image/about/data2.png' %}" width="480px" />
        </div>
        <h3>หน้าแสดงข้อมูลของสัตว์</h3>
        <p style="text-indent:2em">หน้านี้จะประกอบไปด้วย รูปภาพ ข้อมูลทางวิทยาศาสตร์ ข้อมูลทั่วไป และก็ถิ่นที่อยู่อาศัย
            โดยจะมีรูปภาพเพิ่มเติมอยู่ทางด้านล่าง ซึ่งคุณผู้ใช้ก็สามารถช่วยเราเพิ่มรูปภาพให้แก่สัตว์นั้นๆได้นะ :)<br><br>
        </p>

        <hr><br>
        <div style="text-align:center">
            <img src="{% static '/image/about/search.png' %}" width="480px" /> &nbsp;
            <img src="{% static '/image/about/search2.png' %}" width="480px" />
        </div>
        <h3>หน้าค้นหารายชื่อสัตว์</h3>
        <p style="text-indent:2em">คุณผู้ใช้สามารถที่จะใช้หน้านี้ค้นหารายชื่อที่ต้องการได้นะ โดยวิธีใช้ก็ไม่ยากเพียงแค่กรอกคำที่ต้องการค้นหาลงไปแล้วกด SEARCH ได้เลย!!
            หรือจะเลือกค้นหาคำเจาะจงเฉพาะส่วนก็ได้เหมือนกัน<br><br>
        </p>

        <hr><br>
        <div style="text-align:center">
            <img src="{% static '/image/about/add.png' %}" width="480px" /> &nbsp;
            <img src="{% static '/image/about/add2.png' %}" width="480px" />
        </div>
        <h3>หน้าเพิ่มข้อมูลสัตว์</h3>
        <p style="text-indent:2em">หากคุณผู้ใช้พบว่า <i>"ยังไม่มีสัตว์บางตัวในเว็บไซต์นี้เลยนี่ อยากช่วยเพิ่มให้จังเลยน้า"</i> ก็ทำได้เช่นกัน
            โดยคลิกเข้ามาปุ่ม Add Animal ที่ด้านล่างของหน้าเพจ(จะมีอยู่ในทุกๆหน้า) จากนั้นก็กรอกข้อมูลให้ครบถ้วนแล้วกด Submit ได้เลย
            ทางเราจะทำการตรวจสอบความถูกต้องก่อนแล้วจึงจะนำขึ้นหน้าเว็บไซต์ภายหลังนะ<br><br>
        </p>
    </div>
{% endblock %}

park/templates/park/add_data.html
{% extends 'park/base.html' %}
{% load static %}

{% block title %}Add Animal{% endblock %}

{% block style_n_script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static '/JS/add_picture.js' %}"></script>
    <link rel="stylesheet" href="{% static '/css/list.css' %}">
{% endblock %}

{% block header %}
<p id="main_page_head">Add Animal Data</p>
{% endblock %}

{% block content %}
<div class="list_div">
        <a href="{% url 'park:index' %}"><button class="button button_menu">&#127968; Home</button></a>
        <a href="{% url 'park:search' %}"><button class="button button_menu">&#X1F50E; Search</button></a>
        <a href="{% url 'park:animal_list' 'All' %}"><button class="button button_menu">&#X1F4C4; Animal List</button></a>
</div>
        <div class="list_div" style="text-align:left;">
        <form action="{% url 'park:add_animal' %}" method="POST" enctype="multipart/form-data">

        {% csrf_token %}
            <h3>กรอกข้อมูลสัตว์ที่ต้องการเพิ่ม</h3>
            {% if error_message %}<span style='color:red' name="message">{{ error_message }}</span>{% endif %}
            {% if complete_message %}<span style='color:green' name="message">{{ complete_message }}</span>{% endif %}
            <hr><br>

            ชื่อไทย ( thai name ) : <input type="text" name="thai_name" /><br/><br/>
            ชื่ออังกฤษ ( name ) : <input type="text" name="name" /><br/><br/>
            ชั้น ( Class ) : 
            <select name="class_name">
                <option value="Mammal">Mammal</option>
                <option value="Reptile">Reptile</option>
                <option value="Bird">Bird</option>
                <option value="Amphibian">Amphibian</option>
                <option value="Fish">Fish</option>
            </select><br/><br/>
            ลำดับ ( order ) : <input type="text" name="order" /><br/><br/>
            วงศ์ ( family ) : <input type="text" name="family" /><br/><br/>
            <div>ข้อมูลทั่วไป ( info ) : <div><textarea name="info" cols="80" rows="10"></textarea></div></div><br/>
            ถิ่นที่อยู่ ( habitat ) : <div><textarea name="habitat" cols="80" rows="10"></textarea></div><br/>
            รูป : <br>          
   		<div class="input_fields_wrap">
   	    	<div><input type="file" id="pic_file" name="pic_file" accept=".png , .jpg"></div>
		</div>
        <p id="add_alert"></p>
		<button type="button" class="add_field_button">Add More Picture</button><br><br>
		
        <input type="submit" name="submit" value="Submit"/>
        </form>
        </div>
{% endblock %}

park/templates/park/animal_data.html
{% extends 'park/base.html' %}
{% load static %}
{% block title %}{{animal.name}}{% endblock %}

{% block style_n_script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static '/css/popup.css' %}">
    <link rel="stylesheet" href="{% static '/css/data.css' %}">
    <script src="{% static '/JS/popup.js' %}"></script>
    <script src="{% static '/JS/add_picture.js' %}"></script>
<script> 
$(document).ready(function(){
    $(".flip").click(function(){
        $(".panel").slideToggle("fast");
    });
});
</script>

<style> 
.panel, .flip {
    padding: 5px;
    background-color: #e5eecc;
    border: solid 1px #c3c3c3;
    clear: both;
    text-align: center;
    min-width:400px;
    font-size: 20px;
    margin: 0px 20px 0px 20px;
    cursor:pointer;
}

.panel {
    min-width:370px;
    padding: 20px;
    display: none;
}
</style>
{% endblock %}

{% block header %}
    <p id="data_page_head">{{ animal.thai_name }}<br>( {{ animal.name }} )</p>
{% endblock %}
{% block content %}
    <div class="menu">
    <a href="{% url 'park:index' %}"><button class="button bt_home">Home</button></a> >>
    <a href="{% url 'park:animal_list' animal.class_name %}">
        <button class="button bt_{{ animal.class_name }}">{{ animal.class_name }}</button></a> >>
        <button class="button bt_name">{{ animal.name }}</button>
    </div>

    <div class="container_div">
        <div name="data" class="data">
            {% if image_list %}
                <a href="{{ image_list.first.image.url }}" >
                    <img src="{{ image_list.first.image.url }}" width="360px"/></a><br><br>
            {% endif %}
            <table style="font-size:22px">
                <tr><td>ชื่อไทย : </td><td>&nbsp; &nbsp; {{ animal.thai_name }}</td></tr>
                <tr><td>ชื่ออังกฤษ : </td><td>&nbsp; &nbsp; {{ animal.name }}</td></tr>
                <tr><td>ชั้น : </td><td>&nbsp; &nbsp; {{ animal.class_name }}</td></tr>
                <tr><td>ลำดับ : </td><td>&nbsp; &nbsp; {{ animal.order }}</td></tr>
                <tr><td>วงศ์ : </td><td>&nbsp; &nbsp; {{ animal.family }}</td></tr>
            </table>
            <br><br>
        </div>
        <div class="container_info">
        <div name="info" class="info">
            <b>ข้อมูลทั่วไป</b><br>
            {% if animal.info %}
                {{ animal.info|safe }}
            {% else %}
                &nbsp; &nbsp; ไม่มีข้อมูล
            {% endif %}
            <br><br>
        </div>
        <div name="habitat" class="info">
            <b>ถิ่นที่อยู่อาศัย</b>
            <br>
                {% if animal.habitat %}
                    {{ animal.habitat|safe }}
                {% else %}
                    &nbsp; &nbsp; ไม่มีข้อมูล
                {% endif %}
        </div>
        </div>
    </div>

    <div style="margin-bottom:30px;">
    <div class="flip">
        <b>คลิกเพื่อดูรูปภาพเพิ่มเติม</b>
    </div>
    <div class="panel">
        {% for animal_pic in image_list %}
            {% if forloop.counter != 1 %}
                <div style="display:inline-block;">
                    <a href="{{ animal_pic.image.url }}" >
                        <img src="{{ animal_pic.image.url }}" height="200px"/>
                    </a>
                </div>
            {% endif %}
        {% endfor %}
        <div style="display:inline-block;margin-left:30px">
            <a class="btn" data-popup-open="popup-1" href="#">
                <img src="{% static '/image/add_image.png' %}" height="200px"/>
            </a>
        </div>
    </div>



    <div class="popup" data-popup="popup-1">
        <div class="popup-inner">
            <h2>Add Photo</h2>
            <form action="{% url 'park:add_picture' animal.url_name %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input_fields_wrap">
                    <div><input type="file" id="pic_file" name="pic_file" accept=".png , .jpg"></div>
                </div>
                <br>
                <button type="button" class="add_field_button">Add More Picture</button>
                <br><br>
                <input type="submit" name="submit" value="Submit!"/>
                <button data-popup-close="popup-1" href="#">Close</button>
            </form>
            <a class="popup-close" data-popup-close="popup-1" href="#">x</a>
        </div>
    </div>
{% endblock %}

park/templates/park/animal_list.html
{% extends 'park/base.html' %}
{% load static %}

{% block title %}Animal List{% endblock %}

{% block style_n_script %}
    <link rel="stylesheet" href="{% static '/css/list.css' %}">
{% endblock %}

{% block header %}
<p id="main_page_head">Animal List</p>
{% endblock %}

{% block content %}
    <div class="list_div">
    <a href="{% url 'park:index' %}"><button class="button button_menu">&#127968; Home</button></a>
    <a href="{% url 'park:search' %}"><button class="button button_menu">&#X1F50E; Search</button></a>
    </div>

    <div class="list_div">
    {% for class_name in all_class %}
        <a href="{% url 'park:animal_list' class_name %}">
        {% if class_name == class_now %}
        <button class="button sel_bt_{{ class_name }}">
        {% else %}
        <button class="button button_{{ class_name }}">
        {% endif %}    
        {{ class_name }}
        </button></a>
    {% endfor %}
    
    {% if lists %}
    <div style="font-size:20px;margin:15px">มีรายชื่อสัตว์ในหมวดนี้ทั้งหมด {{ lists.count }} รายการ</div>
        {% for animal in lists %}
        
            <a href="{% url 'park:animal_data' animal.url_name %}">
            {% if forloop.counter|divisibleby:2 %}
            <button name='{{ animal.name }}' class="block-list list_{{ animal.class_name }}">
            {% else %}
            <button name='{{ animal.name }}' class="block-list list-left list_{{ animal.class_name }}">
            {% endif %}
            <b class="animal_name">{{ animal.thai_name }} ( {{ animal.name }} )</b><br>
            <div style="float:left">
            <table>
                <tr>
                    <td><b>ชั้น :</b></td><td> &nbsp;{{ animal.class_name }}</td>
                    <td rowspan='3'></td>
                </tr>
                <tr><td><b>ลำดับ :</b></td><td> &nbsp;{{ animal.order }}</td></tr>
                <tr><td><b>วงศ์ :</b></td><td> &nbsp;{{ animal.family }}</td></tr>
            </table></div>
            <div style="float:right"><img src="{{ animal.image.first.image.url }}" width="200px" height="100px"/></div>
            </button></a>
        {% endfor %}
    {% else %}
        <div style="font-size:20px;margin:15px">ไม่มีรายชื่อสัตว์ในหมวดนี้.</div>
    {% endif %}
    </div>
{% endblock %}

park/templates/park/base.html
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    {% block style_n_script %}
    {% endblock %}
</head>
<body>
    <div id="wrapper">
    <div id="header">
        {% block header %}{% endblock %}
    </div>
    <div id="content">
    {% block content %}
    {% endblock %}
    </div>
    <div id="footer">
        <div class="text-footer">By Thakdanai Khunsaen Cpr.E 13 KMUTNB</div>
        <a href="{% url 'park:about' %}">
            <button class="button-footer" name="about"><p>About</p></button>
        </a>
        <a href="{% url 'park:add_animal' %}">
            <button class="button-footer" name="add_animal"><p>Add Animal</p></button>
        </a>
    </div>
    </div>
</body>
</html>

park/templates/park/home.html
{% extends 'park/base.html' %}
{% load static %}
{% block title %}Animal{% endblock %}

{% block style_n_script %}
    <link rel="stylesheet" href="{% static '/css/home.css' %}">
{% endblock %}

{% block header %}
<p id="main_page_head">Animals</p>    
{% endblock %}

{% block content %}
    <div class="list_button">
    <a href="{% url 'park:search' %}"><button class="block-all" name="search">
        <p>&#X1F50E; search</p>
    </button></a>

    <a href="{% url 'park:animal_list' 'All' %}"><button name="All" class="block-left" >
        <p>สัตว์ทั้งหมด<br>All Animals<br>
        <span style="font-size:16px">({{ all_animal }})</span>
    </p></button></a>

    <a href="{% url 'park:animal_list' 'Mammal' %}"><button name="Mammal" class="block-right">
        <p>สัตว์เลี้ยงลูกด้วยนม<br>Mammal<br>
        <span style="font-size:16px">({{ mammal_num }})</span>
    </p></button></a>

    <a href="{% url 'park:animal_list' 'Reptile' %}"><button name="Reptile" class="block-left">
        <p>สัตว์เลื้อยคลาน<br>Reptile<br>
        <span style="font-size:16px">({{ reptile_num }})</span>
    </p></button></a>

    <a href="{% url 'park:animal_list' 'Bird' %}"><button name="Bird" class="block-right">
        <p>สัตว์ปีก<br>Bird<br>
        <span style="font-size:16px">({{ bird_num }})</span>
    </p></button></a>

    <a href="{% url 'park:animal_list' 'Amphibian' %}"><button name="Amphibian" class="block-left">
        <p>สัตว์ครึ่งบกครึ่งน้ำ<br>Amphibian<br>
        <span style="font-size:16px">({{ amphibian_num }})</span>
    </p></button></a>

    <a href="{% url 'park:animal_list' 'Fish' %}"><button name="Fish" class="block-right">
        <p>สัตว์น้ำ<br>Fish<br>
        <span style="font-size:16px">({{ fish_num }})</span>
    </p></button></a>
    </div>
{% endblock %}

park/templates/park/no_page.html
{% extends 'park/base.html' %}
{% load static %}

{% block title %}Page Not Found{% endblock %}

{% block style_n_script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static '/JS/add_picture.js' %}"></script>
    <link rel="stylesheet" href="{% static '/css/list.css' %}">
{% endblock %}

{% block header %}
<p id="data_page_head">Page Not Found</p>
{% endblock %}

{% block content %}
<div class="list_div">
    <br><h1>ไม่พบหน้าเว็บนี้</h1><br>
        <a href="{% url 'park:index' %}"><button class="button button_menu">&#127968; Home</button></a>
        <a href="{% url 'park:search' %}"><button class="button button_menu">&#X1F50E; Search</button></a>
        <a href="{% url 'park:animal_list' 'All' %}"><button class="button button_menu">&#X1F4C4; Animal List</button></a>
</div>
{% endblock %}

park/templates/park/search.html
{% extends 'park/base.html' %}
{% load static %}

{% block title %}Search{% endblock %}

{% block style_n_script %}
    <link rel="stylesheet" href="{% static '/css/list.css' %}">
{% endblock %}

{% block header %}
<p id="main_page_head">Search</p>
{% endblock %}

{% block content %}
<div class="list_div">
<a href="{% url 'park:index' %}"><button class="button button_menu">&#127968; Home</button></a>
<a href="{% url 'park:animal_list' 'All' %}"><button class="button button_menu">&#X1F4C4; Animal List</button></a>
</div>
<div class="list_div">
        <form action="{% url 'park:search' %}" method="get">
            <input type="text" name="word" style="width:400px" />
            <input type="submit" name="submit" value="SEARCH!"/><br/>
            ค้นจาก : 
            <label><input type="radio" name="search" value="name"/> ชื่อสัตว์</label>
            <label><input type="radio" name="search" value="order"/> ลำดับ</label>
            <label><input type="radio" name="search" value="family"/> วงศ์</label>
            <label><input type="radio" name="search" value="info"/> ข้อมูลทั่วไป</label>
            <label><input type="radio" name="search" value="habitat"/> ถิ่นที่อยู่</label>
            <label><input type="radio" name="search" value="all" checked /> ทั้งหมด</label>
        </form>


        {% if word %}
        <div>
            ค้นหาด้วยคำว่า : {{ word }} <br/>

        {% if lists %}
            (พบรายชื่อสัตว์ {{ lists.count }} รายการ)
        </div>
    {% for animal in lists %}
        <a href="{% url 'park:animal_data' animal.url_name %}">
            {% if forloop.counter|divisibleby:2 %}
            <button name="{{ animal.name }}" class="block-list list_{{ animal.class_name }}">
            {% else %}
            <button name="{{ animal.name }}" class="block-list list-left list_{{ animal.class_name }}">
            {% endif %}
            <b class="animal_name">{{ animal.thai_name }} ( {{ animal.name }} )</b><br>
            <table>
                <tr><td><b>ชั้น :</b></td><td> &nbsp;{{ animal.class_name }}</td></tr>
                <tr><td><b>ลำดับ :</b></td><td> &nbsp;{{ animal.order }}</td></tr>
                <tr><td><b>วงศ์ :</b></td><td> &nbsp;{{ animal.family }}</td></tr>
            </table>
            </button></a>
{% endfor %}
{% else %}
    <p>ไม่พบรายชื่อสัตว์ที่ค้นหา.</p>
{% endif %}
{% endif %}
</div>
{% endblock%}
        